### ISSUE TITLE
Coppar prossesing

### ISSUE THREAD

**Issue by mur202** [danielstuart14/Altis-Life#1]
Coppar prossesing isnt working. Im not sure about the other prossesing places but i dont think that they work either

**Comment by danielstuart14** [comment]
Which version are you using? 4.1(pull-request2)?
Can you attach your Client & Server RPT logs?

**Comment by mur202** [comment]
The processing message does not appear I it is because the name of the coppar is incorrect.
coppar name in master file: copper_unrefined
coppar name in prossesing file: life_inv_Unrefined

as you see its not the same :D Just figured that I would report this to help the community out

**Comment by danielstuart14** [comment]
Thx! This should fix: https://github.com/danielstuart14/Altis-Life/commit/1717f7d721f8b26f8878760fa3c15fba5ad70e5c
