### ISSUE TITLE
Clothing Shop Issues 

### ISSUE THREAD

**Issue by sargken** [danielstuart14/Altis-Life#10]
http://imgur.com/I5Y6Pdo

There are 2 issues here, since my screen resolution my menu is really close stuck together and idk if we could use safezones for the dialog to help it. 

The screen to view clothes is on a weird angle.

**Comment by danielstuart14** [comment]
Monitor res.?

**Comment by sargken** [comment]
1366 x 768

**Comment by PiscisSwimeatus** [comment]
Im getting the same on 1920x1080 and normal interface size

**Comment by danielstuart14** [comment]
Will check this out, here it's normal. Can you guys send me client logs and configuration files?

**Comment by danielstuart14** [comment]
As said, here it's normal... Will close until someone post here Client RPT logs + ArmA 3 config. file.

**Comment by sargken** [comment]
ArmA 3 Config file?

**Comment by sargken** [comment]
http://pastebin.com/AWWFKSJK

**Comment by sargken** [comment]
What arma 3 config file do you need

**Comment by danielstuart14** [comment]
Arma3.cfg that is on: Documents/Arma3

**Comment by sargken** [comment]
http://pastebin.com/pQzFYsaq 

If this is all you need you can reopen this issue?

**Comment by sargken** [comment]
http://pastebin.com/3Re5JGRW 

What i did try to do is add in the setvectorup [0,0,1]; hoping that it would eliminate the issue of everything being tilted. But that did not work.

**Comment by Heavybob** [comment]
https://github.com/danielstuart14/Altis-Life/pull/31 I didn't fix the resolution bug but I did fix the camera angle bug and primary weapon holstering while in shop. Just waiting on merge.

**Comment by sargken** [comment]
How did you fix the camera bug?

**Comment by danielstuart14** [comment]
Fixed? If not, I'll reopen.

**Comment by sargken** [comment]
@Heavybob does that fix the camera angle along with the gun showing up as not holstered.

**Comment by Heavybob** [comment]
It does fix a camera issue, it does not focus properly on headgear and vests while holding a primary. Its just one of the the many bugs, sorry if I mislead anyone.
