### ISSUE TITLE
Money Glitch

### ISSUE THREAD

**Issue by sargken** [danielstuart14/Altis-Life#11]
Had a report of a guy testing on my server and you can keep taking out money from atm even if you don't have the money in your account. I will look into this more tomorrow, just felt like posting this tonight. I haven't tried to reproduce but will try tomorrow.

**Comment by danielstuart14** [comment]
Yes, I'd seen this before. Sometimes player's bank gets to zero and then he can take all the money he wants from atm... I'll need logs.

**Comment by clackd1amond** [comment]
It happens when you a buy a vehicle, for which there are no configs for selling/unimpouding, trunk capacity etc., which are stated in Config_Vehicles.hpp

**Comment by sargken** [comment]
Really thats strange but sounds about right.

**Comment by clackd1amond** [comment]
Yeah, that's very strange, but it's true. The easiest way of duping, had some cases of it on my server :)

**Comment by danielstuart14** [comment]
Try this: https://github.com/danielstuart14/Altis-Life/commit/32f0ac7c834bd2ab26823a8993228a858fdfe0bf
Latest commit on v4.2 branch

**Comment by clackd1amond** [comment]
Nah, man. You can leave the 'inherit'-thing, it doesn't break anything. The thing that glitches the money is the absence of the classname of the vehicle itself. So, to six this, "veh_class_name : Default {};" should be enough.

**Comment by danielstuart14** [comment]
hmm, makes sense. But'll let without inherit, it's better.
About the bug then, I'll create a check. If it doesn't found the class for vehicle, it auto-uses default one.

**Comment by clackd1amond** [comment]
Yeah, the check would be awesome! Waiting for commit :)

**Comment by danielstuart14** [comment]
Try this: https://github.com/danielstuart14/Altis-Life/commit/cee05d2c902b54268d0abd4241157147d4d29e47

**Comment by sargken** [comment]
What about for owners and it tells them which vehicles aren't defined properly in the Vehicles Config?

**Comment by danielstuart14** [comment]
FIXED! https://github.com/danielstuart14/Altis-Life/commit/4c5cd6b08028bb4376544e044e3810a9826b15c6

**Comment by clackd1amond** [comment]
It fixed the money issue, but now it has something new. When storing the vehicle without a config to the garage and then you unimpound it, it spawns unlocked and now you can't store it back.

**Comment by danielstuart14** [comment]
Here it's working. You should sync with latest commits.

**Comment by clackd1amond** [comment]
Synced with all the commits. Still the keys don't appear in my keychain after vehicle unimpund

**Comment by Heavybob** [comment]
Dan, I have been following along what you have been doing for the last few months and I really love what your putting together. Keep up to good work.

**Comment by danielstuart14** [comment]
Cheers :beers:
