### ISSUE TITLE
RTP Error #1

### ISSUE THREAD

**Issue by sargken** [danielstuart14/Altis-Life#12]
Error in expression <queryResult","_key","_return","_loop"];
params ["_queryStmt",["_mode",1,[0]],["_
  Error position: params ["_queryStmt",["_mode",1,[0]],["_
  Error Params: Type Number, expected Bool
File life_server\Functions\MySQL\fn_asyncCall.sqf, line 15

**Comment by danielstuart14** [comment]
Are you on latest version?

**Comment by sargken** [comment]
http://pastebin.com/XeeWvPim

**Comment by sargken** [comment]
I should be that's my asyncCall

**Comment by danielstuart14** [comment]
Sync with latest commits...
https://github.com/danielstuart14/Altis-Life/commit/36256809ff53604ddab0b720f515d6416a1ec0aa
