### ISSUE TITLE
Error in Vehicleshopbuy

### ISSUE THREAD

**Issue by sargken** [danielstuart14/Altis-Life#13]
When i bought a vehicle i get an error with showscripterrors enabled if(_exit) exitWith {}; _exit is undefined. I see that its only defined in a conditional so maybe it needs to be set to false initally? Its on line 30.

**Comment by danielstuart14** [comment]
Already defined: https://github.com/danielstuart14/Altis-Life/commit/9c6c85d624be4d72bb4ed66d10644184a4ead0a3
