### ISSUE TITLE
Supply system for weapons

### ISSUE THREAD

**Issue by sargken** [danielstuart14/Altis-Life#14]
Its a suggestion and u have the knowledge to do it is adding a supply system to gun shops with if you set it to 10 guns if a person buys one there is only 9 left. Possibly also a timer to refresh the supply.

**Comment by danielstuart14** [comment]
Didn't get it... It's like a max amount of guns a player can buy in a shop, or the max amount of guns the shop can sell to any player?

**Comment by sargken** [comment]
The max ammount of a certain gun that shop can sell to anyone. Once supply for the gun runs out then you cant buy it.

**Comment by clackd1amond** [comment]
I think, it's amount of guns the shop can sell to any player. It's a great idea for RP. You have to supply, e.g. iron, wood and glass to the shop, and this shop creates a certain amount of weapons depending of the amount supplied. Of course, there is an extra scripts and, I thinks, an additional table in the database. But it would restrict the weapon spreading on Altis? You want weapon? Go farm some resourses.

**Comment by sargken** [comment]
Well to supply the shop you could make a system like arma 2 had with factorys and they could supply the shops you make then then sell to the  desired shop for profit. Also it could be done for vehicles.

**Comment by sargken** [comment]
Im on my phone, when i get home i will post a more detailed description of what i mean.

**Comment by danielstuart14** [comment]
@sargken Maybe I add this as an optional feature in the future. I'll need think about the approach.
@clackd1amond It's a good idea, so, the gun shop won't be anymore a shop, but a gun builder. 

About the gun builder idea, it doesn't need a new table in database. I liked more the idea of providing the items to the gun shop then setting an max amount.

**Comment by clackd1amond** [comment]
Yes, it would be perfect. But if we won't use database, the available amount won't be available anymore after the restart.

**Comment by danielstuart14** [comment]
That's right, but isn't better request the items for each purchase then storing it on shop?

**Comment by sargken** [comment]
Ok so this was my initial idea, is you go to the gunstore  1 and the M16 well say has 10 in stock, you go and buy one now there is only 9. To refill the stock in the gunstore you have to go to a gun smith or weapon factory "what ever you want to call it" from there you have to buy into the factory and hire workers, $300 each. The more workers you have the less time it takes to build the gun. Once the gun is built you can directly take it and have it in your inventory, or you can sell it to a gun shop. Depending on the supply of the gunshop the selling price would fluctuate. Its a supply and demand setup. Well say gun store 1 has 9 of a certain gun in stock and gun store 2 had 3. Selling to gunstore 3 you would make more profit then selling to gun store 1.

**Comment by danielstuart14** [comment]
Okay, it's on my TODO list.

**Comment by Angrygargamel** [comment]
so it would be semi-self-crafting for weapons then.... taking the items to the gundealer and let him make your weapon...
sounds good... would buy it... ^^

**Comment by Heavybob** [comment]
This suggestion reminds me of the Peristent World crafting system for Mount and Blade: Warband. I could see it working that players would need to stock each weapon for them to be purchasable. Could be neat I guess.

**Comment by sargken** [comment]
Yeah if any of you have played on arma 2 taki life or and of those thats was the way it was setup and was pretty neat. Until you have some people the could afford the factory's to make them and they got rich. Was all fun though cause you got to try and bust them.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis

**Comment by Heavybob** [comment]
*Repost all issues to this git*
https://github.com/ArmaLife/Altis/issues

This Git is being discontinued.
