### ISSUE TITLE
License/side/level checks for Virtual Shops

### ISSUE THREAD

**Issue by clackd1amond** [danielstuart14/Altis-Life#15]
It would be very useful to add license, side and level checks to the class VirtualShops in Config_Master.hpp, e.g. for only medics have access to medic shops, where they get supplies to heal people. Civilians mustn't be able to buy stuff there otherwise they will abuse it. It would be very helpful to add those checks like for the gunstores:
side = "";
license = "";
level[] = { "", "", -1, "" };

**Comment by danielstuart14** [comment]
That's right! Will work on it.
Also, I'm going to split Config_Master in two more files.

**Comment by Heavybob** [comment]
Probs not the right place to voice this but the same thing should be done with textures for cars too. Even a define on the price for each unique car.

**Comment by danielstuart14** [comment]
https://github.com/danielstuart14/Altis-Life/commit/a4aa01f2944851d46d8371b942c746a8ab1232b6 :D

**Comment by clackd1amond** [comment]
yay! thank you, man!
