### ISSUE TITLE
Error in expression

### ISSUE THREAD

**Issue by sargken** [danielstuart14/Altis-Life#17]
Error in expression <me","_color","_plate","_query","_sql"];
params [
["_uid","",[""]],
["_side","",[>
  Error position: <params [
["_uid","",[""]],
["_side","",[>
  Error Params: Type String, expected Bool
File life_server\Functions\MySQL\fn_insertVehicle.sqf, line 9

**Comment by danielstuart14** [comment]
https://github.com/danielstuart14/Altis-Life/commit/8454c00e7e4527bf2ca96e99affad765bb02fb17
