### ISSUE TITLE
Gear selling prices

### ISSUE THREAD

**Issue by sargken** [danielstuart14/Altis-Life#18]
The location of the prices for selling gear is strange it is in config master. Wouldn't it make more since to add it in the config weapons as an another array next to the buy prices for weapons.

**Comment by sargken** [comment]
sellArray[] thats what its called in master.

**Comment by clackd1amond** [comment]
I don't think it's neccessary. Personally I set all the sell weapon prices to zero to prevent dupings. I'd suggest to remove the sell gear option at all as it is very easy method of duping.

**Comment by danielstuart14** [comment]
yes, it's on my to-do list.
Will add the sell price in the same array.

About dupe, we just need to set a delay action.

**Comment by Heavybob** [comment]
Dan, think you could make a trello so we can see your to-do list?

**Comment by danielstuart14** [comment]
https://trello.com/b/9urCslRT/altis-life

**Comment by Heavybob** [comment]
Yay you adopted my suggestion :+1:

**Comment by danielstuart14** [comment]
https://github.com/danielstuart14/Altis-Life/commit/648243df7fae88a1c7e12aa8d9f75ae1edbf90f1
https://github.com/danielstuart14/Altis-Life/commit/4148a294067221ed8e370772bebfae6d3bf38296
:beers:

**Comment by danielstuart14** [comment]
ps: If someone wants to add sellprices missing, I will be glad.
(Magazines must stay -1)
