### ISSUE TITLE
fn_vehicleShopBuy.sqf license

### ISSUE THREAD

**Issue by mur202** [danielstuart14/Altis-Life#19]
} foreach _licenses;
if(_exit) exitWith {}>
18:55:56   Error position: <foreach _licenses;
if(_exit) exitWith {}>
18:55:56   Error foreach: Type String, expected Array
18:55:56 File mpmissions\__CUR_MP.altis\core\shops\fn_vehicleShopBuy.sqf, line 30
18:56:00 Error in expression <_Shop_Veh_NoLicense"; _exit = true;};
} foreach _licenses;
if(_exit) exitWith {}>
18:56:00   Error position: <foreach _licenses;
if(_exit) exitWith {}>
18:56:00   Error foreach: Type String, expected Array
18:56:00 File mpmissions\__CUR_MP.altis\core\shops\fn_vehicleShopBuy.sqf, line 30

This pops up in RPT when you try to buy with the latest changes

**Comment by sargken** [comment]
Did u edit ur mission and add any licenses.

**Comment by mur202** [comment]
?

**Comment by sargken** [comment]
Have you edited you local mission file.

**Comment by sargken** [comment]
Paste your config for vehicles on pastebin and post it here.

**Comment by mur202** [comment]
Yes but nothing that would effect that part. + 18:56:00 File mpmissions__CUR_MP.altis\core\shops\fn_vehicleShopBuy.sqf, line 30

There are errors in the file.

**Comment by sargken** [comment]
Just because thats where its throwing the error that doesnt mean its located there.

**Comment by mur202** [comment]
http://pastebin.com/G7WVdNdc , It worked fine before i updated to the latest changes.
CfgVehicles to LifeCfgVehicles etc

**Comment by sargken** [comment]
https://github.com/danielstuart14/Altis-Life/commit/2cde3773198be6c2661b33becfd1ed1823241cec

**Comment by sargken** [comment]
You need to make your license section in that look like this. The format was updated to an array to allow to check for multiple licenses. The above commit should help.

**Comment by mur202** [comment]
yeah I saw this before. And I updated it to allow multiple licenses but I guess I did not save lol.

**Comment by sargken** [comment]
Hey at least youll get it workin.

**Comment by mur202** [comment]
yup, thanks :p
Now I have to the file over again because I did not save:D
