### ISSUE TITLE
Starting cash

### ISSUE THREAD

**Issue by mur202** [danielstuart14/Altis-Life#2]
Well i notice that the starting cash doesnt work. Even though i change it it doesnt work. I start with 2500 each time even though i have this in my configuration.sqf 

	case civilian: {
		BANK = 125000; //Starting Bank Money
		life_paycheck = 35; //Paycheck Amount
	};

**Comment by danielstuart14** [comment]
Can you test it now?
Just let me know if it works... If you still getting only 2500, then, attach your RPTs please.

**Comment by mur202** [comment]
It does not work Client RPT: http://pastebin.com/wRMQCcNh
Server RPT http://pastebin.com/iVwxrAa9

**Comment by danielstuart14** [comment]
Okay, can you try something for me? (I'm without an windows machine now, so, I can't test it.)

But, just open "fn_insertRequest.sqf" which is on "life_server/Functions/MySQL/"
Edit this:
```
params [
	["_uid","",[""]],
	["_name","",[""]],
	["_money",0,[""]],
	["_bank",2500,[""]],
	["_returnToSender",objNull,[objNull]]
];
```
to this:
```
params [
	"_uid",
	"_name",
	["_money",0],
	["_bank",2500],
	["_returnToSender",objNull,[objNull]]
];
```

**Comment by mur202** [comment]
Works fine with that change
