### ISSUE TITLE
Suggestion : Missing License When buying Vehicle

### ISSUE THREAD

**Issue by sargken** [danielstuart14/Altis-Life#21]
This is another suggestion for when buying a vehicle and if you are missing a license it just says missing license, i think doing a string setup with some formatted text saying what license is missing would be better. Let me know what you guys think.

**Comment by danielstuart14** [comment]
Yeah, that was what I had on mind, but I was lazy...
Next week I'll start working on all the stuff missing...

**Comment by sargken** [comment]
I'm just trying to put everything out there to see what you think.

**Comment by danielstuart14** [comment]
https://github.com/danielstuart14/Altis-Life/commit/fe2703b2f7bc9cf73ae219f841f7a10083cbc815 :smile:

**Comment by sargken** [comment]
Sweet
