### ISSUE TITLE
Better gunshop / car shop Suggestion

### ISSUE THREAD

**Issue by Heavybob** [danielstuart14/Altis-Life#23]
The default item purchasing system in altis needs a face lift, especially since we have things like virtual arsenal now supported in arma 3. I am proposing an overhall of the existing clothing shop to add support for primary and secondary weapons + attachment + default ammo configs for weapons because I am starting to find it really annoying scrolling to find the correct ammo / sniper rifles on some servers. Maybe even mark items with an icon to show they are dlc would be pretty sweet. Same thing goes for the car store.

**Comment by Heavybob** [comment]
I have taken a look at the clothing shop and yes its very possible to put in primary and secondarys into  it. Having a few minor issues trying to achieve this but I am sure someone will read this and attempt it.

**Comment by sargken** [comment]
Yes currently the clothing shop is kind of bugged, https://github.com/danielstuart14/Altis-Life/issues/10

**Comment by Heavybob** [comment]
I am having a crack myself at using a altered version of the clothing shop for my primary weapons, just trying to tweak the camera to look in the correct position and the inclusion of default magazines. with purchase.

**Comment by danielstuart14** [comment]
To auto-include magazines with weapon you should intersect magazines array from weaponCfg with magazines your're selling on your shop.
Something like that:
```
_weaponMags = (getArray (configFile >> "CfgWeapons" >> _weapon >> "magazines")) arrayIntersect (M_CONFIG(getArray,"WeaponShops",_shop,"items"));
```

**Comment by danielstuart14** [comment]
I'm thinking in change the Classes, and add the mags in the same array with weapon.
So, it wouldn't show mags anymore on shop. When you buy a weapon, it would gives you 2 mags. Then, to buy more, you would just need to select the weapon and click on Buy Mags. It would calculate then the magazine price from something like 10~5% of weapon price.

**Comment by sargken** [comment]
That could work but what about grenade launchers, or launchers in general. I think another possible avenue would be to create an extension to the dialog that when you bought the gun another dialog opens up right next to the main one and that shows the primary weapons and handgun and has a list of mags that this gun can possibly take.

**Comment by sargken** [comment]
Because if you have it automatically, if you want to buy tracers lets say it wont ever give you any of those just the standard stanag.

**Comment by sargken** [comment]
Tying into the https://github.com/danielstuart14/Altis-Life/issues/14 how would you be able to have the supply system, if it auto give you the magazines. If you expand the limitation to not just the weapons but also items like mags so there is only a certain amount of ammo for a certain gun until the stocks are resupplied.

**Comment by danielstuart14** [comment]
You could then just add these extra ammos as weapons. Just as it's now.
But I like the dialog idea. It should open only when there's more than one magazine id on the array.

I'm going to travel tomorrow in the morning. Monday I'll give you guys an update.

**Comment by sargken** [comment]
Ok sounds good. I just personally don't like the idea of it automatically giving the player the magazines. You should be able to know what the gun shoots if your going to use it, is my philosophy.

**Comment by danielstuart14** [comment]
First I'm going to get this magazine stuff working. Then, we think about supply system.
And Idk if it'll work as you want, cuz there're some issues.

About standard magazines, this will be an option. 
You'll be able to disable it, as pretty much all my changes, in Config_Master.hpp

**Comment by sargken** [comment]
Ok so the automatic giving of mags can be disabled. :+1:

**Comment by Heavybob** [comment]
Glad some people agree with me. Probs want to define the amount of mags given with each gun or at least a default of 1 mag per gun.

**Comment by Heavybob** [comment]
Going to wait til @sargken applys his changes to the clothing shop then I shall run a test commit for my solution to weapons shop.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis

**Comment by Heavybob** [comment]
*Repost all issues to this git*
https://github.com/ArmaLife/Altis/issues

This Git is being discontinued.
