### ISSUE TITLE
Vehicle Inventory/Trunk

### ISSUE THREAD

**Issue by Heavybob** [danielstuart14/Altis-Life#24]
I noticed in the database structure that Vehicle Inventory/Trunk does have an inventory collum though in this build its not used. Wondering if it was going to be worked in in the future. 

Thanks

**Comment by danielstuart14** [comment]
Maybe, but I'm not going to work on this, at least now.

**Comment by sargken** [comment]
I may try and work on this if time opens up, it doesnt seem too out of the span i can handle.

**Comment by danielstuart14** [comment]
great, I'll be glad to merge then.

**Comment by sargken** [comment]
Want to reopen this?

**Comment by Heavybob** [comment]
Re open plz :+1:

**Comment by danielstuart14** [comment]
I'm using issues tab to remember what I have to do, let's make it clean at least for now.

**Comment by sargken** [comment]
Just assign it to me when its open, otherwise.

**Comment by sargken** [comment]
I like that tag.

**Comment by Heavybob** [comment]
Needs more dragons bro.

**Comment by AveUrsus** [comment]
By the way - may be it will be better to disable trunk opening from vehicle if we disable it with players in range? (Y inventory dupe) 1 comment in keyhandler and its done.

**Comment by Heavybob** [comment]
Drop a merge request if you fixed that issue.

**Comment by Heavybob** [comment]
@sargken How you doing with this request?

**Comment by sargken** [comment]
I was actually just about to start working on it. I had some midterms to study for sorry.

**Comment by Heavybob** [comment]
Screw education, just do it.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis

**Comment by Heavybob** [comment]
*Repost all issues to this git*
https://github.com/ArmaLife/Altis/issues

This Git is being discontinued.
