### ISSUE TITLE
aborting or lose connecting

### ISSUE THREAD

**Issue by wokieman** [danielstuart14/Altis-Life#26]
hi mate in my server when someone abort or lose the connection they spawn with 5k without gear,u know why this happening?

**Comment by Heavybob** [comment]
Send me your steam details and I'll take a look.

**Comment by danielstuart14** [comment]
Server and client logs

**Comment by wokieman** [comment]
heavybob my steam is http://steamcommunity.com/profiles/76561198130842594/
and daniel here is extdblog https://www.dropbox.com/s/neu1pe495dpyu3d/extdb%20log.log?dl=0
and server log https://www.dropbox.com/s/2kebgqs3og82emj/arma3-server-console-09-01-2016-21-00-01.log?dl=0 btw this never happen with me but where i can check my client log? thanks in advance.

**Comment by Heavybob** [comment]
Hey Thyssen,

I have sent you a friend request and I am taking a look at the logs.

**Comment by wokieman** [comment]
ok i found if anyone joins on civ slot 6 spawn naked with 5k on bank but after restart i spawn again in that slot and spawn fine and didint made any changes... wtf

**Comment by danielstuart14** [comment]
Error:
```
20:03:59 Error in expression <ariable["BIS_fnc_MP_queue",[],TRUE];

{
_x setVariable["sellers",[],true];
} for>
20:03:59   Error position: <_x setVariable["sellers",[],true];
} for>
20:03:59   Error Undefined variable in expression: _x
20:03:59 File life_server\init.sqf, line 116
20:03:59 Error in expression <,[],true];
} foreach [Dealer_1,Dealer_2,Dealer_3];
};
};

[] spawn TON_fnc_initH>
20:03:59   Error position: <Dealer_3];
};
};

[] spawn TON_fnc_initH>
20:03:59   Error Undefined variable in expression: dealer_3
20:03:59 File life_server\init.sqf, line 117
20:03:59 Error in expression < do {
case civilian: {
_packet pushBack life_is_arrested;
};
};

_packet remoteE>
20:03:59   Error position: <life_is_arrested;
};
};

_packet remoteE>
20:03:59   Error Undefined variable in expression: life_is_arrested
20:03:59 File mpmissions\__cur_mp.Altis\core\session\fn_updateRequest.sqf, line 22
20:03:59 Error in expression <ayerUID player,(profileName),playerSide,life_cash,life_atmbank];
_array = [];
_f>
20:03:59   Error position: <life_cash,life_atmbank];
_array = [];
_f>
20:03:59   Error Undefined variable in expression: life_cash
20:03:59 File mpmissions\__cur_mp.Altis\core\session\fn_updateRequest.sqf, line 7
```
Will take a look.

**Comment by danielstuart14** [comment]
As I see, you did a mistake with your local branch.
Not a life bug.
