### ISSUE TITLE
<null> Weapon Shop Error

### ISSUE THREAD

**Issue by Heavybob** [danielstuart14/Altis-Life#30]
Not exactly a game breaking bug but if you define a weapons name wrong, it will display as *null*.

Would be better if it just said nothing or be definable in Config_Master for example: 
You made a mistake or *Missing Content* for users who don't have a specific mod installed. 

I'll attach a picture in a sec. 
![images akamai steamusercontent](https://cloud.githubusercontent.com/assets/4519067/12218384/be0491c8-b771-11e5-96f2-5111c510f31e.jpg)

**Comment by danielstuart14** [comment]
Not an issue
