### ISSUE TITLE
Housing Broken?

### ISSUE THREAD

**Issue by Heavybob** [danielstuart14/Altis-Life#32]
I'll drop some rpt logs in a few hours but when I checked the housing system maybe a day ago, it was still not working properly. Conformation from anyone on this?

**Comment by danielstuart14** [comment]
I'm finishing my arma 3 download, will take a look later.

**Comment by Heavybob** [comment]
Right o dan

**Comment by Heavybob** [comment]
Any update dan? I have been busy all day and haven't checked yet.

**Comment by danielstuart14** [comment]
working here, I bought a house, unlocked it, turned the lights on, and then sold. No rpt errors.
