### ISSUE TITLE
Knock down problem

### ISSUE THREAD

**Issue by crackhead** [danielstuart14/Altis-Life#34]
We are currently testing the current 4.1 here we noticed the following problems :

if one Knock down a person we get the error error General error in the expressive core / functions / fn_keyhandler.sqf line 106

**Comment by Heavybob** [comment]
CTRL + R as CIV last time I looked a few months ago only knocks out the targeted player and does not rob them as intended. I'll jump on 4.2 and check if this is still the case.

**Comment by Heavybob** [comment]
Confirmed, issue exists in 4.2 will upload error in a sec.

**Comment by danielstuart14** [comment]
Can you post RPT here?

**Comment by danielstuart14** [comment]
Oops

**Comment by crackhead** [comment]
i allredy fixed it {} :D

**Comment by Heavybob** [comment]
Sure dan, I'll post an RPT. Give me a few hours. Crackhead if you fix something, you should share it with everyone so things can be better for everyone.

**Comment by clackd1amond** [comment]
An older code still works for me :) (I have Shift+V for knockout):
	case 47: {
        if(_shift) then {_handled = true;};
        if(_shift && playerSide != independent && !isNull cursorTarget && cursorTarget isKindOf "Man" && isPlayer cursorTarget && alive cursorTarget && cursorTarget distance player < 4 && speed cursorTarget < 1) then
        {
            if((animationState cursorTarget) != "Incapacitated" && (currentWeapon player == primaryWeapon player OR currentWeapon player == handgunWeapon player) && currentWeapon player != "" && !life_knockout && !(player getVariable["restrained",false]) && !life_istazed) then
            {
                [cursorTarget] spawn life_fnc_knockoutAction;
            };
        };
    };

**Comment by danielstuart14** [comment]
I'm focusing on new features (Look my open issue)
If someone fixed it, will be good to share using pull-request feature.

**Comment by Heavybob** [comment]
Thanks Clack, I'll test it and submit a commit.

**Comment by danielstuart14** [comment]
Can someone test it?
https://github.com/danielstuart14/Altis-Life/commit/29a3b4992944594ccbeb87647d9d5e26def3a2c5

**Comment by clackd1amond** [comment]
@danielstuart14 I tested it, it doesn't work. Try mine.

**Comment by danielstuart14** [comment]
Are you sure? Because the difference between they are just that I added brackets for better reading.

**Comment by clackd1amond** [comment]
Yes, Dan, I'm sure. I tested it yesterday. When I reverted back to my code, it began to work again.

**Comment by danielstuart14** [comment]
Okay, just one more question. hehehe
Are you using the right key?

**Comment by danielstuart14** [comment]
https://github.com/danielstuart14/Altis-Life/commit/3847894e7e0afa72dda3c2815fcd569462da45c0

**Comment by clackd1amond** [comment]
Of course I use the right key. LOL :D

**Comment by Heavybob** [comment]
Tested, good work dan, all fixed.

**Comment by danielstuart14** [comment]
Thanks to @clackd1amond instead me.
