### ISSUE TITLE
Car Garage get out car

### ISSUE THREAD

**Issue by crackhead** [danielstuart14/Altis-Life#35]
We are currently testing the current 4.1 here we noticed the following problems :

if you wont to park out a car we get the error '..._VEH_Color",_index,true]; in the file core/vehicle/fn_colorVehicle.sqf line 36

**Comment by Heavybob** [comment]
This is fixed in 4.2

**Comment by danielstuart14** [comment]
fixed on 4.2

**Comment by crackhead** [comment]
do you have a changelog
