### ISSUE TITLE
Latest Version bugs

### ISSUE THREAD

**Issue by crackhead** [danielstuart14/Altis-Life#37]
http://www.pic-upload.de/view-29402766/Screenshot_11.jpg.html
http://www.pic-upload.de/view-29402767/Screenshot_1.jpg.html
http://www.pic-upload.de/view-29402768/Screenshot_2.jpg.html
http://www.pic-upload.de/view-29402769/Screenshot_4.jpg.html

**Comment by danielstuart14** [comment]
RPT logs would be good.
Is it v4.2?

**Comment by crackhead** [comment]
yes downloadet 8 o´clock
Server RPT:
http://www.file-upload.net/download-11201853/arma3server_2016-01-11_21-02-20.rpt.html
Client RPT:
http://www.file-upload.net/download-11201857/arma3_2016-01-11_21-02-07.rpt.html

**Comment by danielstuart14** [comment]
same here
