### ISSUE TITLE
Press Esc Error

### ISSUE THREAD

**Issue by crackhead** [danielstuart14/Altis-Life#38]
NEXT :D but so one good work
http://www.pic-upload.de/view-29403724/Screenshot_6.jpg.html

**Comment by danielstuart14** [comment]
all the errors you reported are about life_atmcash variable that has been corrupted by some reason.
I didn't find these errors. Probably you merged something that broke this variable.

**Comment by Heavybob** [comment]
This error was in a previous build of altis 4.1 back in November. I recall this existing but it has since been fixed.

**Comment by clackd1amond** [comment]
'life_atmcash' became 'life_atmbank' in 4.0. maybe that's the problem.
