### ISSUE TITLE
Tickets

### ISSUE THREAD

**Issue by mur202** [danielstuart14/Altis-Life#4]
Whenever a cop tries to ticket another player nothing happens and the copinteraction menu would just close

**Comment by danielstuart14** [comment]
Hmm ok. It doesn't show any message/notification on game? (Ex: searching...)
Can you attach Client & Server RPT logs?

**Comment by mur202** [comment]
It does not show in the Client RPT: http://pastebin.com/wRMQCcNh
Server RPT http://pastebin.com/iVwxrAa9

You can use my old  RPT because it didnt work there eaither.

**Comment by danielstuart14** [comment]
But did you try search someone when debugging this RPT? It'll only show on RPTs if you tried it and it failed.

**Comment by mur202** [comment]
This time i did: http://pastebin.com/Kz3jinv9

**Comment by danielstuart14** [comment]
https://github.com/danielstuart14/Altis-Life/commit/2c52b5c5985d8110509456ead83716f69164734b

**Comment by mur202** [comment]
Thanks
