### ISSUE TITLE
Persistent wanted system (suggestion)

### ISSUE THREAD

**Issue by clackd1amond** [danielstuart14/Altis-Life#43]
Please, add the persistent wanted system with the ability for cops to add to wanted list manually. I really miss this feature :)

**Comment by AveUrsus** [comment]
clackd1amond: note from my expirience -
we MUST check is someone in wanted list, when he join server, if we do not wanted list be 1000k lines in a while =)
Every check is database query -> we create DB lags on servers with 40+ ppl
/*Its only my opinion*/

**Comment by clackd1amond** [comment]
Had no issues with this with 75 players in earlier versions, but now I can't get it to work...

**Comment by danielstuart14** [comment]
it's possible, but previous versions of persistent wanted list were very bugged.
You can get the commits on my altis-life-old repo. (Branch: itsyuka)
