### ISSUE TITLE
Robbing the fed reserve bug

### ISSUE THREAD

**Issue by clackd1amond** [danielstuart14/Altis-Life#44]
Bank robbing isn't working properly. When you blow up the safe and open its dialog it won't let you take the gold. It says "You can't store anything but gold bars in the safe".

**Comment by Heavybob** [comment]
If you are alone on the server, you are able to breach everything until you get to the safe last time I checked. Will jump on now to test.

**Comment by Heavybob** [comment]
Just jumped on with 4.2 Release Build with just myself and tried to open the safe with zero errors. I will test later with more players on my server but I cannot see that error.

**Comment by danielstuart14** [comment]
RPT erros or I can't fix it.

**Comment by danielstuart14** [comment]
Should fix, if not, just with RPT.
https://github.com/danielstuart14/Altis-Life/commit/110958c71a0ccbfde8e649995c320a0775215a7e

**Comment by clackd1amond** [comment]
Confirmed fixed. That thing is case sensitive. Damn...
