### ISSUE TITLE
Unlocking Veh Spam Bug

### ISSUE THREAD

**Issue by Heavybob** [danielstuart14/Altis-Life#45]
If you hold U to unlock a Veh, it will spam unlocking which can affect server performance.

**Comment by clackd1amond** [comment]
I fixed that spam with adding this to the top of the case 22 in keyhandler
[] spawn {life_usekey = true; sleep 0.8; life_usekey = false; };
Than add 'life_usekey = false' to configuration.sqf
Maybe there's more elegant way of fixing this spam :)

**Comment by Heavybob** [comment]
Submit a pull request so we can see what you did.

**Comment by danielstuart14** [comment]
@Heavybob :+1:

**Comment by clackd1amond** [comment]
Here's what I did:
#51 #52

**Comment by danielstuart14** [comment]
Also https://github.com/danielstuart14/Altis-Life/commit/b4b833034703a7f955e41b02aef63579aa2b6e66

**Comment by clackd1amond** [comment]
Yeah, missed that, sorry.
