### ISSUE TITLE
Clothing Shop Passenger Bug

### ISSUE THREAD

**Issue by Heavybob** [danielstuart14/Altis-Life#46]
If you are in the back of a offload (or any other passenger veh with aiming) and open the clothing shop, it works and bugs out the camera. Would suggest to put in a one line to prevent use of the action menu while in Veh

![107410_screenshots_2016-01-14_00001](https://cloud.githubusercontent.com/assets/4519067/12312924/74a90dee-bab7-11e5-8997-6ccc81b8ce49.jpg)

**Comment by danielstuart14** [comment]
https://github.com/danielstuart14/Altis-Life/commit/ccfb149e58f5942013fc4ef51bea7c6656e39e56

**Comment by Heavybob** [comment]
Thanks dan.
