### ISSUE TITLE
Clothing Shop - Scenic Shops

### ISSUE THREAD

**Issue by Heavybob** [danielstuart14/Altis-Life#50]
*Could not come up with a creative name*

As this was accidentally dreamed up during two pull requests and subsequently closed, I have opened this as a suggestion because the concept is valid and needs more discussion. 

Instead of buying cloths in a box void in limbo each store would have a pre-defined "Scenic Shops"
 to buy cloths. 

Dan: Imagine if admin set a building right on this place? Or if a chopper just fall there.

Solution: If the people have a house on the location, they can easily move the location in the config or disable "Scenic Shops" to have the silly void box. If a chopper or players turn up at the location, they are all invisible due to *insert pre existing ton code here* which does not require us to change anything since I already tested that possibility when I make my first commit :+1: . 

*Take a read*
https://github.com/danielstuart14/Altis-Life/pull/48
https://github.com/danielstuart14/Altis-Life/pull/49

**Comment by clackd1amond** [comment]
I just removed the teleport thing, so the player stays near the shop. It's not good when other players watch how a person just disappears in front of them :)

**Comment by danielstuart14** [comment]
afaik only playable units are invisible.
If someone drop a heli on clothing spawn, and leave it, it will show up.

**Comment by danielstuart14** [comment]
idk if it's a good idea. maybe adding an option to disable teleport would be better, as @clackd1amond said.

**Comment by clackd1amond** [comment]
@danielstuart14 yeah, it would be more realistic. We could use that teleport-box for vehicle shops instead :)

**Comment by Heavybob** [comment]
The chances of people actually dropping a chopper at one of those locations would be really tiny *if it was accidental*. If we are using 20 random locations then that number is even lower to affect players. Only thing that could fuck up the current clothing shop is that a player could park a car on the exit of the clothing shop tp. For safety, I would put in a line just to prevent players from taking damage while in the store and 10 seconds after. 

Its designed to prevent people from getting killed while browsing the store, but no mater what is done, some idiot is going to find a way to mess with it. I still opt for Scenic as an option if @sargken would kindly take into account choice for what people want in this thread.

**Comment by sargken** [comment]
@Heavybob What do I need to do? My pullrequest was closed without an explanation to it.

**Comment by Heavybob** [comment]
https://github.com/danielstuart14/Altis-Life/pull/48
@Sargken, read the end of my pull request and you can see why it was closed. 

Pretty much what would need to be done @Sargken is an option for everyone to choose which one they want. 

*inspired from your config_master settings*

/* Clothing Shop settings */
dynamic_regular = false; // true to disable dynamic and void box to purchase at the store npc
dynamic_void = false // true to enable the void box around the player while purchasing clothing. 
dynamic_positions = true; // true to enable the clothing shop scenic locations
dynamic_random = true; // true to enable the clothing shop scenic locations to be random

If the choice was available, would that make everyone happy?

**Comment by sargken** [comment]
Ill do it if Dan gives the ok that that will work.

**Comment by Heavybob** [comment]
@danielstuart14 Options, will you give that the ok?

**Comment by danielstuart14** [comment]
okay, if it doesn't affect the current method.

And config should be something like this:
```
/* Clothing related settings */
clothing_teleport = true; //Enable/Disable teleport preview for clothing shop.
clothing_box = true; //true = preview inside a black box.  false = preview on map.
```

But it needs:
Spawn player in a random location. (Already predef. locations)
Don't break our current method. (It needs to be our default method.)

Also, don't do any change related to AllowDamage or taking vehicles to garage. (I will look this later)
I think, the best way we could do it is to add markers on map, as player spawns.

About vehicles left on these locations, we can set as invisible all units (Except player and light). 
If you want I can do this fix for vehicles on spawn later.

**Comment by Heavybob** [comment]
Thanks @danielstuart14 
@sargken  DO YOUR MAGIC!

**Comment by Heavybob** [comment]
I will add that I would love to put in a song while you are browsing the clothing store to make it more interesting.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis

**Comment by Heavybob** [comment]
Thanks Dan, will move to new revision.

**Comment by Heavybob** [comment]
*Repost all issues to this git*
https://github.com/ArmaLife/Altis/issues

This Git is being discontinued.
