### ISSUE TITLE
Vehicle preview (suggestion)

### ISSUE THREAD

**Issue by clackd1amond** [danielstuart14/Altis-Life#53]
Sometimes new players that don't have a lot of money on them want to see what they buy. They see clothes but they don't see vehicles. Is it possible to create for veh shop a similar preview mode as for the clothes? It would be very helpful and would look awesome.

**Comment by danielstuart14** [comment]
yes, we can do it as clothing shop.
Create a box that spawns the car.

**Comment by clackd1amond** [comment]
Can't wait for this, thank you! :)

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis

**Comment by Heavybob** [comment]
*Repost all issues to this git*
https://github.com/ArmaLife/Altis/issues

This Git is being discontinued.
