### ISSUE TITLE
Housing crates bug

### ISSUE THREAD

**Issue by AveUrsus** [danielstuart14/Altis-Life#54]
After player reconnect crates are not taking safe positions in house.
This can happen: http://images.akamai.steamusercontent.com/ugc/359527056814528781/B2FDF7C6BC8937B306D55C1C412B78BD0C1208DC/

**Comment by clackd1amond** [comment]
Go clean your room :D

**Comment by danielstuart14** [comment]
seems that it is spawning higher than it should.
Then, physics do what it is supposed to.

**Comment by tkcjesse** [comment]
There is also the issue where the crates will catch fire and sink in the ground. Assume this is partially related.

**Comment by danielstuart14** [comment]
https://github.com/danielstuart14/Altis-Life/commit/c1ef33947a113a8129a16783a228c00d7e2b95b0

**Comment by danielstuart14** [comment]
try it, should work.
