### ISSUE TITLE
Revive fee bug

### ISSUE THREAD

**Issue by clackd1amond** [danielstuart14/Altis-Life#55]
No matter what amount you set up in your config for the revive fee, it is always set to 2$ ingame. RPT log:

21:17:32 Error in expression <_deathCamera;

if(life_atmbank > (call life_revive_fee)) then {
life_atmbank = >
21:17:32   Error position: <life_revive_fee)) then {
life_atmbank = >
21:17:32   Error Undefined variable in expression: life_revive_fee
21:17:32 File mpmissions\__CUR_MP.Altis\core\medical\fn_revived.sqf, line 25

**Comment by danielstuart14** [comment]
Tonic screwing up everything...
https://github.com/TAWTonic/Altis-Life/commit/884e9c980ccef3c6336934dc0b918a2bddf05937
