### ISSUE TITLE
Gutting animal bug

### ISSUE THREAD

**Issue by AveUrsus** [danielstuart14/Altis-Life#58]
good morning =)
Got bug with revealing of animal corpse (as i see)
when you kill an animal in hunting zone and press WIN looking on it corpse nothing will happen - i added diag_log in fn_gunanimal.sqf - its not running - starting fn_gather.sqf and exitwith not in zone.

If you press WIN+T gutting will start but something strange occure - on progress bar is written "repairing truck"

**Comment by Heavybob** [comment]
Confirmed, this does happen.

**Comment by danielstuart14** [comment]
yeah, tonic parcial add this hunting feature... I'll look into it.

**Comment by Heavybob** [comment]
*Repost all issues to this git*
https://github.com/ArmaLife/Altis/issues

This Git is being discontinued.
