### ISSUE TITLE
Search vehicle + Search player

### ISSUE THREAD

**Issue by mur202** [danielstuart14/Altis-Life#7]
It does not detect illegal items and this message would pop up even though they had heroin etc: nothing illegal in this vehicle and same with the person

**Comment by mur202** [comment]
( Dont you just love when im reporting bugs the whole time:D )

**Comment by danielstuart14** [comment]
Can you test it now?

**Comment by mur202** [comment]
sure

**Comment by danielstuart14** [comment]
Search Vehicle Fix: https://github.com/danielstuart14/Altis-Life/commit/702f0c35677fc3e01147bffa3de88aed8d83d4f9
Tested and working.

Don't know about player search. Will test it later.

**Comment by mur202** [comment]
Thanks:)

**Comment by fEcAlMaTteR** [comment]
I don't fully understand the macros and config stuff. but i managed to fix the search player (hacky but works)
core/cop/fn_searchClient.sqf line 23
"getNumber(_x >> 'illegal') isEqualTo 1" configClasses (missionConfigFile >> "VirtualItems")
Returns an empty array.  This is the root of the problem with search player.
[CopSearchPlayer.zip](https://github.com/danielstuart14/Altis-Life/files/75263/CopSearchPlayer.zip)
