### ISSUE TITLE
Vehicle Shops Checking for 2 licenses

### ISSUE THREAD

**Issue by sargken** [danielstuart14/Altis-Life#8]
I had a question if you would know is it possible to have the vehicle shop config, inside there you create an array and have it check for multiple licences?

**Comment by danielstuart14** [comment]
Current code doesn't support it. But isn't hard to implement that. 
I like your idea, will try it.

**Comment by danielstuart14** [comment]
https://github.com/danielstuart14/Altis-Life/commit/2cde3773198be6c2661b33becfd1ed1823241cec

**Comment by sargken** [comment]
Great work.
