### ISSUE TITLE
CUP Weapon Sounds Issue

### ISSUE THREAD

**Issue by sargken** [danielstuart14/Altis-Life#9]
Found out when using cup weapons and adding them into the shops, when shooting you will only hear locally shot weapon sounds. If its your friend that shot you wont hear the shots being fired.

**Comment by sargken** [comment]
If you could spot some lights on this that would be great.

**Comment by danielstuart14** [comment]
Let me see if I get it.
If you add an cop weapon (Like taser pistol ou taser rifle) to civilian weapon shop, when civs shoot with these weapons, they don't play the shoot sound globally. Is that?

**Comment by sargken** [comment]
No what we did is we added the weapons to the normal shop like the scar L. I now think it may be a mod issue. Not sure though.

**Comment by sargken** [comment]
Its Mods Fault not mission
